#!/usr/bin/python

import argparse
import re

script_config = {}
class ScriptConf:
    def __init__(self, **entries):
        self.__dict__.update(entries)
scriptConf = ScriptConf(**script_config)


arg_parser = argparse.ArgumentParser(description='Generate a Skills Progression Table')
arg_parser.add_argument(
    '--skills',
    nargs="*",
    action='store',
    dest='skills',
    default= [
      'Acrobatics', 'Appraise', 'Bluff', 'Climb', 'Craft', 'Diplomacy', 'Disable Device', 'Disguise', 'Escape Artist', 'Fly', 'Handle Animal', 'Heal', 'Intimidate', 'Knowledge (arcana)', 'Knowledge (dungeoneering)', 'Knowledge (engineering)', 'Knowledge (geography)', 'Knowledge (history)', 'Knowledge (local)', 'Knowledge (nature)', 'Knowledge (nobility)', 'Knowledge (planes)', 'Knowledge (religion)', 'Linguistics', 'Perception', 'Perform', 'Profession', 'Ride', 'Sense Motive', 'Sleight of Hand', 'Spellcraft', 'Stealth', 'Survival', 'Swim', 'Use Magic Device'
    ],
    help='Use this pid file to determine status'
)

args = arg_parser.parse_args()
scriptConf.levels = 20
scriptConf.skills = args.skills

def skill_link_name( skill_long_name ):
  short_m = re.search( r'([\w|\s]+\()', skill_long_name )
  name = ''
  if short_m:
    name = short_m.group(1)
  else:
    name = skill_long_name
  name = name.replace( ' ', '-' )
  link = "http://www.d20pfsrd.com/skills/{0}/".format( name )
  return link


print '{| class="wikitable"'
print '!colspan="2" | Skill'
for level in range( 1, scriptConf.levels + 1 ):
 print '! {0} '.format( level )
for skill in scriptConf.skills:
  print '|- style="background-color: #FFFACD"'
  print '| rowspan="2"  | [{0} {1}]'.format( skill_link_name( skill ), skill )
  print '| Ranks:'
  for level in range( 0, scriptConf.levels ):
   print '| - '
  print '|- style="background-color: #F0E68C" '
  print '| Total:'
  for level in range( 0, scriptConf.levels ):
   print '| -'

print '|}'
